import { ReservationStatus } from '../../modules/reservation/entities/reservation.entity';

export default [
  {
    userId: 1,
    courtId: 1,
    reservationDate: new Date('2025-01-10'),
    startTime: '10:00',
    endTime: '12:00',
    status: ReservationStatus.COMPLETED,
    note: 'Reservation para historial (Bronce)',
  },
  {
    userId: 1,
    courtId: 2,
    reservationDate: new Date('2025-02-15'),
    startTime: '11:00',
    endTime: '12:30',
    status: ReservationStatus.COMPLETED,
    note: 'Segunda Reservation para historial',
  },
  {
    userId: 1,
    courtId: 1,
    reservationDate: new Date('2026-11-01'),
    startTime: '15:00',
    endTime: '16:30',
    status: ReservationStatus.CONFIRMED,
    note: 'Reservation futura (bloqueo de borrado)',
  },
  {
    userId: 2,
    courtId: 1,
    reservationDate: new Date('2026-05-20'),
    startTime: '09:00',
    endTime: '10:00',
    status: ReservationStatus.PENDING,
    note: 'Reservation pendiente de Payment usuario 2',
  },
  {
    userId: 3,
    courtId: 1,
    reservationDate: new Date('2025-02-15'),
    startTime: '11:00',
    endTime: '12:30',
    status: ReservationStatus.COMPLETED,
    note: 'Segunda Reservation para historial',
  },
  {
    userId: 3,
    courtId: 2,
    reservationDate: new Date('2026-11-01'),
    startTime: '15:00',
    endTime: '16:30',
    status: ReservationStatus.CONFIRMED,
    note: 'Reservation futura (bloqueo de borrado)',
  },
  {
    userId: 3,
    courtId: 1,
    reservationDate: new Date('2026-05-20'),
    startTime: '09:00',
    endTime: '10:00',
    status: ReservationStatus.PENDING,
    note: 'Reservation pendiente de Payment usuario 3',
  },
  {
    userId: 3,
    courtId: 2,
    reservationDate: new Date('2026-11-01'),
    startTime: '15:00',
    endTime: '16:30',
    status: ReservationStatus.CONFIRMED,
    note: 'Reservation futura (bloqueo de borrado)',
  },
  {
    userId: 3,
    courtId: 2,
    reservationDate: new Date('2026-10-01'),
    startTime: '15:00',
    endTime: '16:30',
    status: ReservationStatus.CONFIRMED,
    note: 'Reservation futura (bloqueo de borrado)',
  },
  {
    userId: 3,
    courtId: 2,
    reservationDate: new Date('2026-12-01'),
    startTime: '15:00',
    endTime: '16:30',
    status: ReservationStatus.CONFIRMED,
    note: 'Reservation futura (bloqueo de borrado)',
  },
];
