import { estadoReserva } from "../../modules/reserva/entities/reserva.entity";

export default [
    {
        usuario_id: 1,
        pista_id: 1,
        fecha_reserva: new Date('2025-01-10'),
        hora_inicio: '10:00', 
        hora_fin: '12:00',  
        estado: estadoReserva.FINALIZADA,
        nota: 'Reserva para historial (Bronce)',
    },
    {
        usuario_id: 1,
        pista_id: 2,
        fecha_reserva: new Date('2025-02-15'),
        hora_inicio: '11:00',
        hora_fin: '12:30',  
        estado: estadoReserva.FINALIZADA,
        nota: 'Segunda reserva para historial',
    },
    {
        usuario_id: 1,
        pista_id: 1,
        fecha_reserva: new Date('2026-11-01'),
        hora_inicio: '15:00',
        hora_fin: '16:30',  
        estado: estadoReserva.CONFIRMADA,
        nota: 'Reserva futura (bloqueo de borrado)',
    },
    {
        usuario_id: 2,
        pista_id: 1,
        fecha_reserva: new Date('2026-05-20'),
        hora_inicio: '09:00',
        hora_fin: '10:00',  
        estado: estadoReserva.PENDIENTE,
        nota: 'Reserva pendiente de pago usuario 2',
    },
    {
        usuario_id: 3,
        pista_id: 1,
        fecha_reserva: new Date('2025-02-15'),
        hora_inicio: '11:00',
        hora_fin: '12:30',  
        estado: estadoReserva.FINALIZADA,
        nota: 'Segunda reserva para historial',
    },
    {
        usuario_id: 3,
        pista_id: 2,
        fecha_reserva: new Date('2026-11-01'),
        hora_inicio: '15:00',
        hora_fin: '16:30',  
        estado: estadoReserva.CONFIRMADA,
        nota: 'Reserva futura (bloqueo de borrado)',
    },
    {
        usuario_id: 3,
        pista_id: 1,
        fecha_reserva: new Date('2026-05-20'),
        hora_inicio: '09:00',
        hora_fin: '10:00',  
        estado: estadoReserva.PENDIENTE,
        nota: 'Reserva pendiente de pago usuario 3',
    },
    {
        usuario_id: 3,
        pista_id: 2,
        fecha_reserva: new Date('2026-11-01'),
        hora_inicio: '15:00',
        hora_fin: '16:30',  
        estado: estadoReserva.CONFIRMADA,
        nota: 'Reserva futura (bloqueo de borrado)',
    },
    {
        usuario_id: 3,
        pista_id: 2,
        fecha_reserva: new Date('2026-10-01'),
        hora_inicio: '15:00',
        hora_fin: '16:30',  
        estado: estadoReserva.CONFIRMADA,
        nota: 'Reserva futura (bloqueo de borrado)',
    },
    {
        usuario_id: 3,
        pista_id: 2,
        fecha_reserva: new Date('2026-12-01'),
        hora_inicio: '15:00',
        hora_fin: '16:30',  
        estado: estadoReserva.CONFIRMADA,
        nota: 'Reserva futura (bloqueo de borrado)',
    },
];