import { ReservationStatus } from '../../modules/reservation/entities/reservation.entity';

export default [
  {
    user_id: 1,
    court_id: 1,
    reservation_date: new Date('2025-01-10'),
    start_time: '10:00',
    end_time: '12:00',
    status: ReservationStatus.COMPLETED,
    note: 'Reservation para historial (Bronce)',
  },
  {
    user_id: 1,
    court_id: 2,
    reservation_date: new Date('2025-02-15'),
    start_time: '11:00',
    end_time: '12:30',
    status: ReservationStatus.COMPLETED,
    note: 'Segunda Reservation para historial',
  },
  {
    user_id: 1,
    court_id: 1,
    reservation_date: new Date('2026-11-01'),
    start_time: '15:00',
    end_time: '16:30',
    status: ReservationStatus.CONFIRMED,
    note: 'Reservation futura (bloqueo de borrado)',
  },
  {
    user_id: 2,
    court_id: 1,
    reservation_date: new Date('2026-05-20'),
    start_time: '09:00',
    end_time: '10:00',
    status: ReservationStatus.PENDING,
    note: 'Reservation pendiente de Payment usuario 2',
  },
  {
    user_id: 3,
    court_id: 1,
    reservation_date: new Date('2025-02-15'),
    start_time: '11:00',
    end_time: '12:30',
    status: ReservationStatus.COMPLETED,
    note: 'Segunda Reservation para historial',
  },
  {
    user_id: 3,
    court_id: 2,
    reservation_date: new Date('2026-11-01'),
    start_time: '15:00',
    end_time: '16:30',
    status: ReservationStatus.CONFIRMED,
    note: 'Reservation futura (bloqueo de borrado)',
  },
  {
    user_id: 3,
    court_id: 1,
    reservation_date: new Date('2026-05-20'),
    start_time: '09:00',
    end_time: '10:00',
    status: ReservationStatus.PENDING,
    note: 'Reservation pendiente de Payment usuario 3',
  },
  {
    user_id: 3,
    court_id: 2,
    reservation_date: new Date('2026-11-01'),
    start_time: '15:00',
    end_time: '16:30',
    status: ReservationStatus.CONFIRMED,
    note: 'Reservation futura (bloqueo de borrado)',
  },
  {
    user_id: 3,
    court_id: 2,
    reservation_date: new Date('2026-10-01'),
    start_time: '15:00',
    end_time: '16:30',
    status: ReservationStatus.CONFIRMED,
    note: 'Reservation futura (bloqueo de borrado)',
  },
  {
    user_id: 3,
    court_id: 2,
    reservation_date: new Date('2026-12-01'),
    start_time: '15:00',
    end_time: '16:30',
    status: ReservationStatus.CONFIRMED,
    note: 'Reservation futura (bloqueo de borrado)',
  },
];
