import { UserRole } from '../../modules/users/entities/user.entity';

export default [
  {
    username: 'ResPi',
    name: 'test',
    surname: 'test',
    email: 'test@test.com',
    phone: '634323242',
    password: 'Abc@1234',
    role: UserRole.SUPER_ADMIN,
    isActive: true,
    fecha_registro: new Date('2025-10-23'),
    fecha_ultimo_login: new Date('2025-10-23'),
    fecha_nacimiento: new Date('2007-10-23'),
    direccion: 'C/ Casa al costat de la de Carolina',
  },
  {
    username: 'Mauricio12',
    name: 'mauro',
    surname: 'paco',
    email: 'mauro@test.com',
    phone: '677892736',
    password: 'Abc@1234',
    role: UserRole.SUPER_ADMIN,
    isActive: true,
    fecha_registro: new Date('2025-10-23'),
    fecha_ultimo_login: new Date('2025-10-23'),
    fecha_nacimiento: new Date('2007-10-23'),
    direccion: 'C/ Casa al costat de la de Carolina',
  },
  {
    username: 'el_paco23',
    name: 'clientes',
    surname: 'paco',
    email: 'paco@cliente.com',
    phone: '677823736',
    password: 'Abc@1234',
    role: UserRole.CLIENTE,
    isActive: true,
    fecha_registro: new Date('2025-10-23'),
    fecha_ultimo_login: new Date('2025-10-23'),
    fecha_nacimiento: new Date('2007-10-23'),
    direccion: 'C/ Casa al costat de la de Carolina',
  },
];
